# Azure Developer CLI (azd) configuration for Healthcare MCP Platform
# Deploys infrastructure and MCP server Function Apps
name: healthcare-mcp

metadata:
  template: healthcare-mcp@1.0.0

# Infrastructure configuration
infra:
  provider: bicep
  path: deploy/infra
  module: main

# Service definitions
# ---------------------------------------------------------------------------
# MCP servers are deployed as Docker containers to Azure Function Apps.
# azd's `host: function` does NOT support `language: docker` (only containerapp does),
# so MCP servers are NOT listed here as azd services. Instead:
#   - Bicep provisions the Function Apps (kind: functionapp,linux,container)
#   - The deploy script builds/pushes Docker images and updates container config
#   - Hooks below call the script during `azd up` / `azd deploy`
#
# To deploy containers manually:
#   ./scripts/deploy-mcp-containers.sh              # all servers
#   ./scripts/deploy-mcp-containers.sh npi-lookup    # single server
#   make azure-deploy                                # via Makefile
# ---------------------------------------------------------------------------
services: {}

# Pipeline configuration for CI/CD
pipeline:
  provider: github

# Hooks for custom deployment steps
hooks:
  preprovision:
    shell: sh
    run: |
      echo "=========================================="
      echo "Healthcare MCP Platform - Infrastructure"
      echo "=========================================="
      echo "Environment: ${AZURE_ENV_NAME}"
      echo "Location: ${AZURE_LOCATION}"
      echo ""

  postprovision:
    shell: sh
    run: |
      echo "=========================================="
      echo "Infrastructure deployed successfully!"
      echo "=========================================="
      echo ""
      echo "APIM Gateway URL: ${SERVICE_APIM_GATEWAY_URL}"
      echo "AI Services Endpoint: ${SERVICE_AI_SERVICES_ENDPOINT}"
      echo ""
      echo "MCP Server Endpoints (via APIM passthrough /mcp-pt):"
      echo "  - Reference Data:     ${SERVICE_APIM_GATEWAY_URL}/mcp-pt/reference-data/mcp"
      echo "  - Clinical Research:  ${SERVICE_APIM_GATEWAY_URL}/mcp-pt/clinical-research/mcp"
      echo "  - Cosmos RAG:         ${SERVICE_APIM_GATEWAY_URL}/mcp-pt/cosmos-rag/mcp"
      echo ""
      # Deploy MCP server containers to Function Apps
      echo "Deploying MCP server containers..."
      ./scripts/deploy-mcp-containers.sh

  predeploy:
    shell: sh
    run: |
      echo "Deploying MCP server containers to Azure Function Apps..."
      ./scripts/deploy-mcp-containers.sh

  postdeploy:
    shell: sh
    run: ./scripts/postdeploy.sh
    continueOnError: true
