#!/usr/bin/env bash
# Sync local env variables from current azd environment outputs.
#
# Writes/updates a managed block in .env.local (ignored by git) so local
# workflows (including cosmos-rag) can reuse deployed endpoints.

set -euo pipefail

QUIET=false
if [[ "${1:-}" == "--quiet" ]]; then
  QUIET=true
  shift
fi

if [[ $# -gt 0 ]]; then
  echo "Usage: $0 [--quiet]" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$REPO_ROOT/.env.local"
AZURE_DIR="$REPO_ROOT/.azure"

log() {
  if ! $QUIET; then
    echo "$@"
  fi
}

trim_quotes() {
  local value="$1"
  value="${value//$'\r'/}"
  value="${value#\"}"
  value="${value%\"}"
  printf '%s' "$value"
}

resolve_value() {
  local var_name="$1"
  local value="${!var_name:-}"

  if [[ -z "$value" ]] && command -v azd >/dev/null 2>&1; then
    value="$(azd env get-value "$var_name" --no-prompt 2>/dev/null || true)"
  fi

  trim_quotes "$value"
}

detect_azd_env_name() {
  local env_name="${AZURE_ENV_NAME:-}"

  if [[ -n "$env_name" ]]; then
    printf '%s' "$env_name"
    return 0
  fi

  local config_file="$AZURE_DIR/config.json"
  if [[ -f "$config_file" ]]; then
    env_name="$(sed -n 's/.*"defaultEnvironment":"\([^"]*\)".*/\1/p' "$config_file" | head -n1)"
    if [[ -n "$env_name" ]]; then
      printf '%s' "$env_name"
      return 0
    fi
  fi

  if [[ -d "$AZURE_DIR" ]]; then
    env_name="$(find "$AZURE_DIR" -mindepth 2 -maxdepth 2 -name '.env' -print 2>/dev/null | head -n1 | sed -E 's|.*/.azure/([^/]+)/.env$|\1|')"
  fi
  printf '%s' "$env_name"
}

AZD_ENV_NAME="$(detect_azd_env_name)"
AZD_ENV_FILE=""
if [[ -n "$AZD_ENV_NAME" ]]; then
  AZD_ENV_FILE="$AZURE_DIR/$AZD_ENV_NAME/.env"
fi

if [[ -f "$AZD_ENV_FILE" ]]; then
  # Load azd output values from local file to avoid interactive CLI prompts.
  set -a
  # shellcheck disable=SC1090
  source "$AZD_ENV_FILE"
  set +a
fi

AI_ENDPOINT="$(resolve_value SERVICE_AI_SERVICES_ENDPOINT)"
if [[ -z "$AI_ENDPOINT" ]]; then
  AI_ENDPOINT="$(resolve_value aiServicesEndpoint)"
fi

COSMOS_ENDPOINT="$(resolve_value cosmosDbEndpoint)"
if [[ -z "$COSMOS_ENDPOINT" ]]; then
  COSMOS_ENDPOINT="$(resolve_value COSMOS_DB_ENDPOINT)"
fi

FHIR_SERVER_URL="$(resolve_value fhirServerUrl)"
APIM_GATEWAY_URL="$(resolve_value SERVICE_APIM_GATEWAY_URL)"
AZURE_RESOURCE_GROUP="$(resolve_value AZURE_RESOURCE_GROUP)"

if [[ -z "$AI_ENDPOINT" && -z "$COSMOS_ENDPOINT" && -z "$FHIR_SERVER_URL" && -z "$APIM_GATEWAY_URL" ]]; then
  log "No azd outputs found for local env sync. Skipping .env.local update."
  exit 0
fi

APIM_BASE_URL=""
if [[ -n "$APIM_GATEWAY_URL" ]]; then
  APIM_BASE_URL="${APIM_GATEWAY_URL%/}/mcp-pt"
fi

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

if [[ -f "$OUTPUT_FILE" ]]; then
  awk '
    BEGIN { in_block = 0 }
    /^# BEGIN AZD AUTOGENERATED - DO NOT EDIT$/ { in_block = 1; next }
    /^# END AZD AUTOGENERATED$/ { in_block = 0; next }
    !in_block { print }
  ' "$OUTPUT_FILE" > "$tmp_file"
fi

cat >> "$tmp_file" <<EOF_BLOCK
# BEGIN AZD AUTOGENERATED - DO NOT EDIT
# Generated by scripts/sync-local-env-from-azd.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
AZURE_AI_SERVICES_ENDPOINT=${AI_ENDPOINT}
COSMOS_DB_ENDPOINT=${COSMOS_ENDPOINT}
COSMOS_DB_DATABASE=healthcare-mcp
EMBEDDING_DEPLOYMENT_NAME=text-embedding-3-large
EMBEDDING_DIMENSIONS=3072
FHIR_SERVER_URL=${FHIR_SERVER_URL}
APIM_BASE_URL=${APIM_BASE_URL}
# END AZD AUTOGENERATED
EOF_BLOCK

mv "$tmp_file" "$OUTPUT_FILE"
trap - EXIT

log "Updated $OUTPUT_FILE from azd environment outputs."
if [[ -n "$AI_ENDPOINT" ]]; then
  log "  AZURE_AI_SERVICES_ENDPOINT: $AI_ENDPOINT"
fi
if [[ -n "$COSMOS_ENDPOINT" ]]; then
  log "  COSMOS_DB_ENDPOINT: $COSMOS_ENDPOINT"
fi
